# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd2a73d06765c39e7e67d43de6e4bfa120d0981aeb9584fad4974a53aee2ea7dddf99b93072e2ae2ac4d0a4dd16e5c48a4d2f135f50a104207178f8cd4c7b75a

test:
  secret_key_base: 8fe2afa136cca9238b5241e96347e433be7ccf3b7c40571ae8939b66361c9f8caad304e1b283cd47d38e282acea769c553ab769cd67ba9ac21742fd46d49f691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
